---
# handlers file for web
  - name: my_handler
    copy:
      src: "{{item}}"
      
      dest: /var/www/html/
    loop:
      "{{all_sources}}"

    notify: my_handler2
    changed_when: true
  
  - name: my_handler2
    sysvinit:
      name: "{{package}}"
      state: restarted